/-
  refine_capsule.lean — Refinement-to-code liveness (Option 3).

  This is the Lean side of the Aeneas pipeline. The Rust function `advance`
  (rust/aeneas/capsule.rs) is a DETERMINISTIC good-path scheduler. Aeneas
  extracts it to a pure Lean function; here we reproduce that function and prove
  that the run it generates is a legal `IsRun`, so the EXISTING temporal
  liveness theorem `responsiveness` applies to it verbatim. That is the payoff:
  the full omega-run liveness property L, proved once abstractly, transfers to
  the code-derived deterministic implementation — liveness "lives" in Lean,
  where F/G and infinite runs exist, while the refinement guarantees the Lean
  run faithfully mirrors the Rust.

  We prove, with NO new axioms:
    1. step_advance     : ∀ s, Step s (advance s)        — advance refines Step
    2. detRun_isRun     : Init s0 → IsRun (detRun s0)     — its run is legal
    3. responsiveness_det: liveness L on the code-derived run (corollary of the
                           existing `responsiveness`)
    4. advance_three    : the bounded 3-step witness, directly on `advance`

  Compile together with the development, e.g.:
    cat ltl_capsule.lean refine_capsule.lean > /tmp/combined.lean
    lean /tmp/combined.lean
-/

import ltl_capsule

namespace UefiCapsuleLTL
open Phase

/-- The deterministic good-path scheduler, mirroring the Rust `advance`
    (rust/aeneas/capsule.rs). Every branch corresponds to exactly one `Step`
    constructor, so `advance` is a legal deterministic refinement of `Step`. -/
--LISTING:advance:begin
def advance (s : St) : St :=
  match s.phase with
  | Idle           => s                                    -- stutterIdle
  | CapsuleStaged  => { s with phase := PostReset, resetOccurred := true }
  | PostReset      => { s with phase := Authenticating }
  | Authenticating =>
      if s.capsuleSigValid = true ∧ s.fwVersion < s.capsuleVersion then
        { s with phase := Applied, fwVersion := s.capsuleVersion }
      else
        { s with phase := Rejected, capsulePresent := false }
  | Applied        => { s with phase := Idle, capsulePresent := false, resetOccurred := false }
  | Rejected       => { s with phase := Idle, capsulePresent := false, resetOccurred := false }
--LISTING:advance:end

/-- **Refinement.** Every `advance` step is a real `Step`: the deterministic
    scheduler only ever takes legal transitions. -/
theorem step_advance (s : St) : Step s (advance s) := by
  unfold advance
  cases h : s.phase with
  | Idle           => exact Step.stutterIdle s h
  | CapsuleStaged  => exact Step.reset s h
  | PostReset      => exact Step.beginAuth s h
  | Authenticating =>
      by_cases hc : s.capsuleSigValid = true ∧ s.fwVersion < s.capsuleVersion
      · rw [if_pos hc]; exact Step.apply s h hc.1 hc.2
      · rw [if_neg hc]
        apply Step.reject s h
        -- ¬(sig=true ∧ fw<cap)  ⇒  sig=false ∨ cap≤fw, using only core tactics
        by_cases hs : s.capsuleSigValid = true
        · -- signature valid, so the version guard must have failed
          have hnlt : ¬ (s.fwVersion < s.capsuleVersion) := fun hlt => hc ⟨hs, hlt⟩
          exact Or.inr (Nat.le_of_not_lt hnlt)
        · -- signature not = true, hence = false (Bool)
          exact Or.inl (by cases hb : s.capsuleSigValid <;> simp_all)
  | Applied        => exact Step.finishApplied s h
  | Rejected       => exact Step.finishRejected s h

/-- The deterministic run generated by iterating `advance` from `s0`. This is
    the Lean image of running the Rust `advance` in a loop. -/
def detRun (s0 : St) : Nat → St
  | 0     => s0
  | n + 1 => advance (detRun s0 n)

/-- **The code-derived run is legal.** If `s0` is initial, the deterministic
    `advance`-run is an `IsRun`, so every theorem proved for all runs applies. -/
theorem detRun_isRun {s0 : St} (h : Init s0) : IsRun (detRun s0) := by
  refine ⟨h, ?_⟩
  intro i
  show Step (detRun s0 i) (advance (detRun s0 i))
  exact step_advance (detRun s0 i)

/-- **Refinement-to-code liveness (the payoff).** The existing temporal theorem
    `responsiveness`, proved once for all runs, transfers to the deterministic
    code-derived run: whenever a good capsule is staged at any position `j`, the
    implementation reaches `Applied`. Liveness L now holds of the Rust function,
    via the refinement, with no new proof. -/
theorem responsiveness_det {s0 : St} (h : Init s0) :
    ∀ j, goodStaged (detRun s0) j →
        ∃ k, j ≤ k ∧ (detRun s0 k).phase = Applied := by
  intro j hgood
  exact responsiveness (detRun s0) (detRun_isRun h) j (Nat.zero_le j) hgood

/-- **Safety transfers too.** Authenticity (S) on the code-derived run: the
    implementation never reports a capsule applied unless its signature was
    valid. A corollary of the existing `safety_authentic`, via `detRun_isRun` —
    the same one-line transfer works for R1, R2, G, O. -/
theorem safety_authentic_det {s0 : St} (h : Init s0) :
    ∀ j, (detRun s0 j).phase = Applied → (detRun s0 j).capsuleSigValid = true := by
  intro j
  exact safety_authentic (detRun s0) (detRun_isRun h) j (Nat.zero_le j)

/-- A staged, authentic, strictly-newer state at the state level. -/
def goodState (s : St) : Prop :=
  s.phase = CapsuleStaged ∧ s.capsuleSigValid = true ∧ s.fwVersion < s.capsuleVersion

/-- **Bounded witness, directly on `advance`.** Three deterministic steps from a
    good staged state reach `Applied` — the executable image of the forced
    3-step liveness argument, on the extracted function itself. -/
theorem advance_three {s : St} (hg : goodState s) :
    (advance (advance (advance s))).phase = Applied := by
  obtain ⟨hp, hsig, hver⟩ := hg
  simp only [advance, hp, hsig, hver, and_self, if_true]

end UefiCapsuleLTL
