-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [authvar]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace authvar

/-- [authvar::Phase]
    Source: 'authvar.rs', lines 12:0-18:1
    Visibility: public -/
@[discriminant isize]
inductive Phase where
| Idle : Phase
| Received : Phase
| Verifying : Phase
| Written : Phase
| Refused : Phase

/-- [authvar::{impl core::clone::Clone for authvar::Phase}::clone]:
    Source: 'authvar.rs', lines 11:9-11:14
    Visibility: public -/
def Phase.Insts.CoreCloneClone.clone (self : Phase) : Result Phase := do
  ok self

/-- Trait implementation: [authvar::{impl core::clone::Clone for authvar::Phase}]
    Source: 'authvar.rs', lines 11:9-11:14 -/
@[reducible]
def Phase.Insts.CoreCloneClone : core.clone.Clone Phase := {
  clone := Phase.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [authvar::{impl core::marker::Copy for authvar::Phase}]
    Source: 'authvar.rs', lines 11:16-11:20 -/
@[reducible]
def Phase.Insts.CoreMarkerCopy : core.marker.Copy Phase := {
  cloneInst := Phase.Insts.CoreCloneClone
}

/-- Trait implementation: [authvar::{impl core::marker::StructuralPartialEq for authvar::Phase}]
    Source: 'authvar.rs', lines 11:22-11:31 -/
@[reducible]
def Phase.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Phase := {
}

/-- [authvar::{impl core::cmp::PartialEq<authvar::Phase> for authvar::Phase}::eq]:
    Source: 'authvar.rs', lines 11:22-11:31
    Visibility: public -/
def Phase.Insts.CoreCmpPartialEqPhase.eq
  (self : Phase) (other : Phase) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [authvar::{impl core::cmp::PartialEq<authvar::Phase> for authvar::Phase}]
    Source: 'authvar.rs', lines 11:22-11:31 -/
@[reducible]
def Phase.Insts.CoreCmpPartialEqPhase : core.cmp.PartialEq Phase Phase := {
  eq := Phase.Insts.CoreCmpPartialEqPhase.eq
}

/-- [authvar::{impl core::cmp::Eq for authvar::Phase}::assert_fields_are_eq]:
    Source: 'authvar.rs', lines 11:33-11:35
    Visibility: public -/
def Phase.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Phase) : Result Unit := do
  ok ()

/-- Trait implementation: [authvar::{impl core::cmp::Eq for authvar::Phase}]
    Source: 'authvar.rs', lines 11:33-11:35 -/
@[reducible]
def Phase.Insts.CoreCmpEq : core.cmp.Eq Phase := {
  partialEqInst := Phase.Insts.CoreCmpPartialEqPhase
  assert_fields_are_eq := Phase.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [authvar::St]
    Source: 'authvar.rs', lines 21:0-27:1
    Visibility: public -/
structure St where
  phase : Phase
  stored_time : Std.U64
  req_present : Bool
  req_time : Std.U64
  req_authorized : Bool

/-- [authvar::{impl core::clone::Clone for authvar::St}::clone]:
    Source: 'authvar.rs', lines 20:9-20:14
    Visibility: public -/
def St.Insts.CoreCloneClone.clone (self : St) : Result St := do
  ok self

/-- Trait implementation: [authvar::{impl core::clone::Clone for authvar::St}]
    Source: 'authvar.rs', lines 20:9-20:14 -/
@[reducible]
def St.Insts.CoreCloneClone : core.clone.Clone St := {
  clone := St.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [authvar::{impl core::marker::Copy for authvar::St}]
    Source: 'authvar.rs', lines 20:16-20:20 -/
@[reducible]
def St.Insts.CoreMarkerCopy : core.marker.Copy St := {
  cloneInst := St.Insts.CoreCloneClone
}

/-- [authvar::verify]:
    Source: 'authvar.rs', lines 30:0-42:1
    Visibility: public -/
def verify (s : St) : Result St := do
  let b ← Phase.Insts.CoreCmpPartialEqPhase.eq s.phase Phase.Verifying
  if b
  then
    if s.req_authorized
    then
      if s.stored_time < s.req_time
      then ok { s with phase := Phase.Written, stored_time := s.req_time }
      else ok { s with phase := Phase.Refused, req_present := false }
    else ok { s with phase := Phase.Refused, req_present := false }
  else ok s

/-- [authvar::begin_verify]:
    Source: 'authvar.rs', lines 45:0-51:1
    Visibility: public -/
def begin_verify (s : St) : Result St := do
  let b ← Phase.Insts.CoreCmpPartialEqPhase.eq s.phase Phase.Received
  if b
  then ok { s with phase := Phase.Verifying }
  else ok s

/-- [authvar::advance]:
    Source: 'authvar.rs', lines 54:0-60:1
    Visibility: public -/
def advance (s : St) : Result St := do
  match s.phase with
  | Phase.Idle => ok s
  | Phase.Received => begin_verify s
  | Phase.Verifying => verify s
  | Phase.Written => ok s
  | Phase.Refused => ok s

end authvar
