-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [capsule]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace capsule

/-- [capsule::Phase]
    Source: 'capsule.rs', lines 23:0-30:1
    Visibility: public -/
@[discriminant isize]
inductive Phase where
| Idle : Phase
| CapsuleStaged : Phase
| PostReset : Phase
| Authenticating : Phase
| Applied : Phase
| Rejected : Phase

/-- [capsule::{impl core::clone::Clone for capsule::Phase}::clone]:
    Source: 'capsule.rs', lines 22:9-22:14
    Visibility: public -/
def Phase.Insts.CoreCloneClone.clone (self : Phase) : Result Phase := do
  ok self

/-- Trait implementation: [capsule::{impl core::clone::Clone for capsule::Phase}]
    Source: 'capsule.rs', lines 22:9-22:14 -/
@[reducible]
def Phase.Insts.CoreCloneClone : core.clone.Clone Phase := {
  clone := Phase.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [capsule::{impl core::marker::Copy for capsule::Phase}]
    Source: 'capsule.rs', lines 22:16-22:20 -/
@[reducible]
def Phase.Insts.CoreMarkerCopy : core.marker.Copy Phase := {
  cloneInst := Phase.Insts.CoreCloneClone
}

/-- Trait implementation: [capsule::{impl core::marker::StructuralPartialEq for capsule::Phase}]
    Source: 'capsule.rs', lines 22:22-22:31 -/
@[reducible]
def Phase.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Phase := {
}

/-- [capsule::{impl core::cmp::PartialEq<capsule::Phase> for capsule::Phase}::eq]:
    Source: 'capsule.rs', lines 22:22-22:31
    Visibility: public -/
def Phase.Insts.CoreCmpPartialEqPhase.eq
  (self : Phase) (other : Phase) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [capsule::{impl core::cmp::PartialEq<capsule::Phase> for capsule::Phase}]
    Source: 'capsule.rs', lines 22:22-22:31 -/
@[reducible]
def Phase.Insts.CoreCmpPartialEqPhase : core.cmp.PartialEq Phase Phase := {
  eq := Phase.Insts.CoreCmpPartialEqPhase.eq
}

/-- [capsule::{impl core::cmp::Eq for capsule::Phase}::assert_fields_are_eq]:
    Source: 'capsule.rs', lines 22:33-22:35
    Visibility: public -/
def Phase.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Phase) : Result Unit := do
  ok ()

/-- Trait implementation: [capsule::{impl core::cmp::Eq for capsule::Phase}]
    Source: 'capsule.rs', lines 22:33-22:35 -/
@[reducible]
def Phase.Insts.CoreCmpEq : core.cmp.Eq Phase := {
  partialEqInst := Phase.Insts.CoreCmpPartialEqPhase
  assert_fields_are_eq := Phase.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [capsule::St]
    Source: 'capsule.rs', lines 33:0-40:1
    Visibility: public -/
structure St where
  phase : Phase
  fw_version : Std.U64
  capsule_present : Bool
  capsule_version : Std.U64
  capsule_sig_valid : Bool
  reset_occurred : Bool

/-- [capsule::{impl core::clone::Clone for capsule::St}::clone]:
    Source: 'capsule.rs', lines 32:9-32:14
    Visibility: public -/
def St.Insts.CoreCloneClone.clone (self : St) : Result St := do
  ok self

/-- Trait implementation: [capsule::{impl core::clone::Clone for capsule::St}]
    Source: 'capsule.rs', lines 32:9-32:14 -/
@[reducible]
def St.Insts.CoreCloneClone : core.clone.Clone St := {
  clone := St.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [capsule::{impl core::marker::Copy for capsule::St}]
    Source: 'capsule.rs', lines 32:16-32:20 -/
@[reducible]
def St.Insts.CoreMarkerCopy : core.marker.Copy St := {
  cloneInst := St.Insts.CoreCloneClone
}

/-- [capsule::authenticate]:
    Source: 'capsule.rs', lines 45:0-57:1
    Visibility: public -/
def authenticate (s : St) : Result St := do
  let b ← Phase.Insts.CoreCmpPartialEqPhase.eq s.phase Phase.Authenticating
  if b
  then
    if s.capsule_sig_valid
    then
      if s.fw_version < s.capsule_version
      then
        ok { s with phase := Phase.Applied, fw_version := s.capsule_version }
      else ok { s with phase := Phase.Rejected, capsule_present := false }
    else ok { s with phase := Phase.Rejected, capsule_present := false }
  else ok s

/-- [capsule::reset]:
    Source: 'capsule.rs', lines 64:0-70:1
    Visibility: public -/
def reset (s : St) : Result St := do
  let b ← Phase.Insts.CoreCmpPartialEqPhase.eq s.phase Phase.CapsuleStaged
  if b
  then ok { s with phase := Phase.PostReset, reset_occurred := true }
  else ok s

/-- [capsule::begin_auth]:
    Source: 'capsule.rs', lines 72:0-78:1
    Visibility: public -/
def begin_auth (s : St) : Result St := do
  let b ← Phase.Insts.CoreCmpPartialEqPhase.eq s.phase Phase.PostReset
  if b
  then ok { s with phase := Phase.Authenticating }
  else ok s

/-- [capsule::advance]:
    Source: 'capsule.rs', lines 83:0-90:1
    Visibility: public -/
def advance (s : St) : Result St := do
  match s.phase with
  | Phase.Idle => ok s
  | Phase.CapsuleStaged => reset s
  | Phase.PostReset => begin_auth s
  | Phase.Authenticating => authenticate s
  | Phase.Applied => ok s
  | Phase.Rejected => ok s

end capsule
