-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [secureboot]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace secureboot

/-- [secureboot::Revs]
    Source: 'secureboot.rs', lines 15:0-18:1
    Visibility: public -/
@[discriminant isize]
inductive Revs where
| Nil : Revs
| Cons : Std.U64 → Revs → Revs

/-- [secureboot::{impl core::clone::Clone for secureboot::Revs}::clone]:
    Source: 'secureboot.rs', lines 14:9-14:14
    Visibility: public -/
def Revs.Insts.CoreCloneClone.clone (self : Revs) : Result Revs := do
  match self with
  | Revs.Nil => ok Revs.Nil
  | Revs.Cons __self_0 __self_1 =>
    let i ← lift (core.clone.impls.CloneU64.clone __self_0)
    let r ← Revs.Insts.CoreCloneClone.clone __self_1
    ok (Revs.Cons i r)
partial_fixpoint

/-- Trait implementation: [secureboot::{impl core::clone::Clone for secureboot::Revs}]
    Source: 'secureboot.rs', lines 14:9-14:14 -/
@[reducible]
def Revs.Insts.CoreCloneClone : core.clone.Clone Revs := {
  clone := Revs.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [secureboot::{impl core::marker::StructuralPartialEq for secureboot::Revs}]
    Source: 'secureboot.rs', lines 14:16-14:25 -/
@[reducible]
def Revs.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Revs := {
}

/-- [secureboot::{impl core::cmp::PartialEq<secureboot::Revs> for secureboot::Revs}::eq]:
    Source: 'secureboot.rs', lines 14:16-14:25
    Visibility: public -/
def Revs.Insts.CoreCmpPartialEqRevs.eq
  (self : Revs) (other : Revs) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | Revs.Nil => ok true
    | Revs.Cons __self_0 __self_1 =>
      match other with
      | Revs.Nil => ok true
      | Revs.Cons __arg1_0 __arg1_1 =>
        let b ← lift (core.cmp.impls.PartialEqU64.eq __self_0 __arg1_0)
        if b
        then Revs.Insts.CoreCmpPartialEqRevs.eq __self_1 __arg1_1
        else ok false
  else ok false
partial_fixpoint

/-- Trait implementation: [secureboot::{impl core::cmp::PartialEq<secureboot::Revs> for secureboot::Revs}]
    Source: 'secureboot.rs', lines 14:16-14:25 -/
@[reducible]
def Revs.Insts.CoreCmpPartialEqRevs : core.cmp.PartialEq Revs Revs := {
  eq := Revs.Insts.CoreCmpPartialEqRevs.eq
}

/-- [secureboot::{impl core::cmp::Eq for secureboot::Revs}::assert_fields_are_eq]:
    Source: 'secureboot.rs', lines 14:27-14:29
    Visibility: public -/
def Revs.Insts.CoreCmpEq.assert_fields_are_eq (self : Revs) : Result Unit := do
  ok ()

/-- Trait implementation: [secureboot::{impl core::cmp::Eq for secureboot::Revs}]
    Source: 'secureboot.rs', lines 14:27-14:29 -/
@[reducible]
def Revs.Insts.CoreCmpEq : core.cmp.Eq Revs := {
  partialEqInst := Revs.Insts.CoreCmpPartialEqRevs
  assert_fields_are_eq := Revs.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [secureboot::append]:
    Source: 'secureboot.rs', lines 21:0-26:1
    Visibility: public -/
def append (a : Revs) (b : Revs) : Result Revs := do
  match a with
  | Revs.Nil => ok b
  | Revs.Cons h t => let r ← append t b
                     ok (Revs.Cons h r)
partial_fixpoint

/-- [secureboot::Phase]
    Source: 'secureboot.rs', lines 29:0-35:1
    Visibility: public -/
@[discriminant isize]
inductive Phase where
| Idle : Phase
| Received : Phase
| Verifying : Phase
| Updated : Phase
| Refused : Phase

/-- [secureboot::{impl core::clone::Clone for secureboot::Phase}::clone]:
    Source: 'secureboot.rs', lines 28:9-28:14
    Visibility: public -/
def Phase.Insts.CoreCloneClone.clone (self : Phase) : Result Phase := do
  match self with
  | Phase.Idle => ok Phase.Idle
  | Phase.Received => ok Phase.Received
  | Phase.Verifying => ok Phase.Verifying
  | Phase.Updated => ok Phase.Updated
  | Phase.Refused => ok Phase.Refused

/-- Trait implementation: [secureboot::{impl core::clone::Clone for secureboot::Phase}]
    Source: 'secureboot.rs', lines 28:9-28:14 -/
@[reducible]
def Phase.Insts.CoreCloneClone : core.clone.Clone Phase := {
  clone := Phase.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [secureboot::{impl core::marker::StructuralPartialEq for secureboot::Phase}]
    Source: 'secureboot.rs', lines 28:16-28:25 -/
@[reducible]
def Phase.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Phase := {
}

/-- [secureboot::{impl core::cmp::PartialEq<secureboot::Phase> for secureboot::Phase}::eq]:
    Source: 'secureboot.rs', lines 28:16-28:25
    Visibility: public -/
def Phase.Insts.CoreCmpPartialEqPhase.eq
  (self : Phase) (other : Phase) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [secureboot::{impl core::cmp::PartialEq<secureboot::Phase> for secureboot::Phase}]
    Source: 'secureboot.rs', lines 28:16-28:25 -/
@[reducible]
def Phase.Insts.CoreCmpPartialEqPhase : core.cmp.PartialEq Phase Phase := {
  eq := Phase.Insts.CoreCmpPartialEqPhase.eq
}

/-- [secureboot::{impl core::cmp::Eq for secureboot::Phase}::assert_fields_are_eq]:
    Source: 'secureboot.rs', lines 28:27-28:29
    Visibility: public -/
def Phase.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Phase) : Result Unit := do
  ok ()

/-- Trait implementation: [secureboot::{impl core::cmp::Eq for secureboot::Phase}]
    Source: 'secureboot.rs', lines 28:27-28:29 -/
@[reducible]
def Phase.Insts.CoreCmpEq : core.cmp.Eq Phase := {
  partialEqInst := Phase.Insts.CoreCmpPartialEqPhase
  assert_fields_are_eq := Phase.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [secureboot::St]
    Source: 'secureboot.rs', lines 37:0-43:1
    Visibility: public -/
structure St where
  phase : Phase
  dbx : Revs
  req_present : Bool
  req_revs : Revs
  req_authorized : Bool

/-- [secureboot::update]:
    Source: 'secureboot.rs', lines 46:0-63:1
    Visibility: public -/
def update (s : St) : Result St := do
  let b ← Phase.Insts.CoreCmpPartialEqPhase.eq s.phase Phase.Verifying
  if b
  then
    if s.req_authorized
    then
      let r ← Revs.Insts.CoreCloneClone.clone s.req_revs
      let r1 ← append s.dbx r
      ok { s with phase := Phase.Updated, dbx := r1 }
    else ok { s with phase := Phase.Refused, req_present := false }
  else ok s

/-- [secureboot::begin_verify]:
    Source: 'secureboot.rs', lines 65:0-71:1
    Visibility: public -/
def begin_verify (s : St) : Result St := do
  let b ← Phase.Insts.CoreCmpPartialEqPhase.eq s.phase Phase.Received
  if b
  then ok { s with phase := Phase.Verifying }
  else ok s

/-- [secureboot::advance]:
    Source: 'secureboot.rs', lines 74:0-80:1
    Visibility: public -/
def advance (s : St) : Result St := do
  match s.phase with
  | Phase.Idle => ok s
  | Phase.Received => begin_verify s
  | Phase.Verifying => update s
  | Phase.Updated => ok s
  | Phase.Refused => ok s

end secureboot
